### ISSUE TITLE
VL53L1_SetUserROI

### ISSUE THREAD

**Issue by kkellner-cl** [melopero/Melopero_VL53L1X#1]
I would like to reduce the ROI (reduce the FoV from 27° to 10° or so).   I see the raw C API has a function VL53L1_SetUserROI which looks to do what I need, but it doesn't look like its exposed via Python wrapper.   Any chance this API can be added to the Python API?

**Comment by melopero** [comment]
Hello. 
Run `sudo pip3 install melopero-vl53l1x --upgrade` , you should find a setROI() function in the release 0.2.2.

Regards, 
Melopero Team

**Comment by kkellner-cl** [comment]
Is release 0.2.2 that contains the setROI() python function checked into github?   I'm looking around and don't see it, but maybe I'm looking in the wrong place.

**Comment by melopero** [comment]
Hello, 
Release 0.2.2 is now available on GitHub. 
Regards, 
Melopero Team

**Comment by kkellner-cl** [comment]
This is great, its working perfect.   I needed to measure the water level in a pipe and the normal 27 degree FOV was too wide.   Changing to 4x4 in the center via `setROI(6, 9, 9, 6)` worked great.   Thanks for adding the python wrapper to this API.
