### ISSUE TITLE
How to catch: ioctl(I2C_RDWR) in i2c_read: Remote I/O error

### ISSUE THREAD

**Issue by kkellner-cl** [melopero/Melopero_VL53L1X#2]
I need to gracefully handle the condition when the sensor is not connected.

When this code runs:
```
sensor = mp.VL53L1X()
```

I get about 100 of this error to stdout:
```
ioctl(I2C_RDWR) in i2c_read: Remote I/O error
```
since the VL53L1X class constructor returns without exception and with no way to get the `status`, there is no way to tell that an error occurred.   Is there a way to verify that the sensor is connected to I2C and/or trap the error when it isn't found?

**Comment by leoli51** [comment]
Hi @kkellner-cl you are completely right. I added an Exception raising mechanism to the constructor and all dangerous functions. There is still a small problem: if you disconnect the sensor while it is trying to get a measurement it will try to read from the sensor until the measurement time is out and it will print a lot of the above errors to stdout. Then it will raise the exception. I will fix this issue soon.
